export interface RateType {
  [key: string]: number;
}
export type OptionsType<T> = {
  from: T;
  to: T;
  input: number;
  output?: "raw" | "result";
};

export type LengthTypes =
  | "m"
  | "mm"
  | "cm"
  | "nm"
  | "µm"
  | "dm"
  | "dam"
  | "hm"
  | "in"
  | "km"
  | "mi"
  | "mil"
  | "yd"
  | "ft"
  | "fm"
  | "am"
  | "ly";
export type TempTypes =
  | "tpw"
  | "kelvin"
  | "celsius"
  | "fahrenheit"
  | "rankine"
  | "reaumur";

export type AngleTypes =
  | "radian"
  | "degree"
  | "grad"
  | "minute"
  | "second"
  | "gon"
  | "sign"
  | "mil"
  | "revolution"
  | "circle"
  | "turn"
  | "quadrant"
  | "rightangle"
  | "sextant";

export type WeightAndMassTypes =
  | "kg"
  | "g"
  | "mg"
  | "t-metric"
  | "lbs"
  | "oz"
  | "ct"
  | "t-us"
  | "t-uk"
  | "Eg"
  | "Pg"
  | "Tg"
  | "Gg"
  | "Mg"
  | "hg"
  | "dag"
  | "dg"
  | "cg"
  | "µm"
  | "ng"
  | "pg"
  | "fg"
  | "ag"
  | "dalton"
  | "kg-force-square-second/meter"
  | "kip"
  | "slug"
  | "p-force-square-second/foot"
  | "p-troy"
  | "p-apothecary"
  | "pdl"
  | "t-assay-us"
  | "t-assay-uk"
  | "kt-metric"
  | "cwt-metric"
  | "hundredweight-us"
  | "hundredweight-uk"
  | "qr-us"
  | "qr-uk"
  | "stone-us"
  | "stone-uk"
  | "t"
  | "pwt"
  | "s-apothecary"
  | "gr"
  | "gamma"
  | "talent-hebrew"
  | "mina-hebrew"
  | "shekel-hebrew"
  | "bekan-hebrew"
  | "gerah-hebrew"
  | "talent-greek"
  | "mina-greek"
  | "tetradrachma-greek"
  | "didrachma-greek"
  | "drachma-greek"
  | "denarius-roman"
  | "assarion-roman"
  | "quadrans-roman"
  | "lepton-roman"
  | "planck-mass"
  | "electron-mass"
  | "muon-mass"
  | "proton-mass"
  | "neutron-mass"
  | "deuteron-mass"
  | "earth-mass"
  | "sun-mass";

export type DataStorageTypes =
  | "bit"
  | "nibble"
  | "byte"
  | "character"
  | "word"
  | "mapm-word"
  | "quadruple-word"
  | "block"
  | "kilobit"
  | "kilobyte"
  | "megabit"
  | "megabyte"
  | "gigabit"
  | "gigabyte"
  | "terabit"
  | "terabyte"
  | "petabit"
  | "petabyte"
  | "exabit"
  | "exabyte"
  | "floppy-disk-3.5-DD"
  | "floppy-disk-3.5-HD"
  | "floppy-disk-3.5-ED"
  | "floppy-disk-5.25-DD"
  | "floppy-disk-5.25-HD"
  | "zip-100"
  | "jaz-1gb"
  | "cd-80-min";
